"""
Proposal schema.

A Proposal is a concrete offer or counter-offer generated by an agent during
the negotiation phase of the orchestration workflow.
"""

from __future__ import annotations

from decimal import Decimal
from enum import StrEnum
from uuid import UUID, uuid4
from datetime import datetime, timezone

from pydantic import BaseModel, Field, ConfigDict


class ProposalStatus(StrEnum):
    DRAFT = "draft"
    SUBMITTED = "submitted"
    ACCEPTED = "accepted"
    REJECTED = "rejected"
    COUNTERED = "countered"
    EXPIRED = "expired"


class Proposal(BaseModel):
    """
    An offer or counter-offer emitted by an agent during negotiation.

    Note: all financial figures are *simulated* for workflow demonstration
    purposes and carry no real monetary value.
    """

    model_config = ConfigDict(frozen=True)

    proposal_id: UUID = Field(default_factory=uuid4)
    transaction_id: UUID = Field(..., description="Parent transaction reference")
    originated_by: str = Field(..., description="Agent name that created this proposal")

    status: ProposalStatus = ProposalStatus.DRAFT

    # ── Offer terms (all mocked) ─────────────────────────────────────────────
    proposed_amount: Decimal = Field(..., gt=Decimal(0))
    proposed_rate: Decimal | None = Field(
        default=None,
        ge=Decimal("0.01"),
        le=Decimal("100.00"),
        description="APR % for loan products; None for non-loan proposals",
    )
    proposed_term_months: int | None = Field(
        default=None, ge=1, le=360, description="Loan term in months, if applicable"
    )

    rationale: str = Field(default="", max_length=2000, description="Agent reasoning")
    conditions: list[str] = Field(
        default_factory=list,
        description="Conditions that must be met for this proposal to be valid",
    )

    created_at: datetime = Field(default_factory=lambda: datetime.now(timezone.utc))
    expires_at: datetime | None = Field(default=None)
    metadata: dict[str, str] = Field(default_factory=dict)

    @property
    def is_expired(self) -> bool:
        if self.expires_at is None:
            return False
        return datetime.now(timezone.utc) > self.expires_at
